apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-admin
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-admin
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list
      - get
      - delete
      - create
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-admin
subjects:
- kind: ServiceAccount
  name: k8s-admin
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: k8s-admin
spec:
  serviceAccountName: k8s-admin
  containers:
  - image: nabsul/k8s-admin:v003
    name: kube
